site_name: Echo Sounding Simulator
repo_name: Echo Sounding Simulator
repo_url: https://github.com/matthew-buglass/echo_sounding_simulator
site_author: Matthew Buglass

docs_dir: docs_source
site_dir: docs

theme:
  name: "material"

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: false

markdown_extensions:
  - pymdownx.arithmatex:
        generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
