name: Ensure Docs are Up to Date

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: validate-docs
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Rebuild docs
      run: bash build_docs_site.sh
    # We check if the number of changes are greater than 1 because the sitemap will always change
    - name: Check that no differences exist
      run: |
        num_diffs=$(git diff --shortstat docs | cut -d' ' -f2)
        echo "Number of differences in the docs directory $num_diffs"
        if [[ "$num_diffs" -gt 1 ]]; then
          exit 1;
        else
          exit 0;
        fi